### ISSUE TITLE
arch support ?

### ISSUE THREAD

**Issue by SamLebarbare** [srh/rethinkdb-package-builder#2]
Hello Sam,

It's possible to support/add arm64 arch?

**Comment by srh** [comment]
If you can find a sane way to make it work (cross-compiling? qemu for testing?), go for it.

**Comment by srh** [comment]
It seems like https://engineering.docker.com/2019/04/multi-arch-images/ implies it would be pretty doable.

**Comment by srh** [comment]
It seems pretty easy if you switch to docker edge (and play with it a bit).  I'm giving it a run now, maybe it'll work.

**Comment by SamLebarbare** [comment]
I have crosscompiled from ubuntu two month ago. 
with:
`CROSS=arm-linux-gnueabihf
export CC=$CROSS-gcc
export CXX=$CROSS-g++
export LD=$CROSS-ld
export AR=$CROSS-ar
export RANLIB=$CROSS-ranlib`

i have made some changes in the rethink pkg scripts. I can provide you a patch, but if you have made changes in the pkg process (updated oudated urls)
I will retry with the last codebase this weekend.

**Comment by SamLebarbare** [comment]
(i'am not a big fan of docker, but for your CI/CD process it's perhaps the best way)

**Comment by srh** [comment]
I am working on it right now.  I've been making a few tweaks to the setup.rb script:

- Add an --arch option, of course.
- Use docker buildx.  It seems necessary to follow the `buildx create` steps at https://docs.docker.com/docker-for-mac/multi-arch/ .
- Change the basic rdbcheckout and fetch scripts to use a v2.4.x commit, because v2.3.7's configure script doesn't recognize aarch64.

**Comment by srh** [comment]
Okay, with buildx it's not seeing local images and I don't care to fight it right now.  I put my changes in https://github.com/srh/rethinkdb-package-builder/tree/buildx .

**Comment by gabor-boros** [comment]
Since the packages can be built on an arm64/v8 machine, I guess this issue is not an issue anymore

**Comment by srh** [comment]
Oh, thanks, I'll close this I guess.
